const VENUES=['桐生','戸田','江戸川','平和島','多摩川','浜名湖','蒲郡','常滑','津','三国','びわこ','住之江','尼崎','鳴門','丸亀','児島','宮島','徳山','下関','若松','芦屋','福岡','唐津','大村'];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const yen=n=>Number.isFinite(+n)?`${(+n).toLocaleString()}円`:'--';const pct=n=>Number.isFinite(+n)?`${(+n).toFixed(1)}%`:'--';
function rows(x){if(Array.isArray(x))return x;for(const k of['data','races','items','venues','results'])if(Array.isArray(x?.[k]))return x[k];return[]}
function venueName(r){return r?.venue_name||r?.venue||r?.stadium_name||r?.place_name||r?.jyo_name||''}
function raceNo(r){return +(r?.race_no||r?.race||r?.race_number||0)}
function deadline(r){return r?.deadline||r?.close_time||r?.deadline_at||r?.cutoff||''}
function parseDeadline(r){const raw=deadline(r);if(!raw)return null;const now=new Date();if(/^\d{1,2}:\d{2}$/.test(raw)){const [h,m]=raw.split(':').map(Number);const d=new Date(now);d.setHours(h,m,0,0);return d}const d=new Date(raw);return Number.isNaN(+d)?null:d}
function decision(r){const stake=+(r?.stake_total_yen??r?.stake??0);const d=String(r?.decision??'').toUpperCase();if(d==='ENTER'&&stake>0)return'enter';if(['WATCH','WAIT','OBSERVE','様子見'].includes(d))return'watch';return'skip'}
function stateText(s){return s==='enter'?'✅ 予想完了':s==='watch'?'👀 様子見':'⏸ 見送り'}
async function api(path){const c=new AbortController();const t=setTimeout(()=>c.abort(),7000);try{const r=await fetch(path,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error(String(r.status));return await r.json()}finally{clearTimeout(t)}}
let races=[],currentVenue='';
function venueRaces(name){return races.filter(r=>venueName(r)===name).sort((a,b)=>raceNo(a)-raceNo(b))}
function classifyVenueRace(list){const now=new Date();const future=list.filter(r=>{const d=parseDeadline(r);return d&&d>=now}).sort((a,b)=>+parseDeadline(a)-+parseDeadline(b));if(future.length)return future[0];return list[list.length-1]||null}
function isPast(r,current){const rn=raceNo(r),cr=raceNo(current);if(rn&&cr)return rn<cr;const d=parseDeadline(r);return d?d<new Date():false}
function renderVenues(){const grouped=new Map(VENUES.map(v=>[v,venueRaces(v)]));$('#venues').innerHTML=VENUES.map(name=>{const list=grouped.get(name)||[];const cur=classifyVenueRace(list);const rn=cur?raceNo(cur):0;const dl=cur?deadline(cur):'';return `<button class="venue ${cur?'hasData':''}" data-v="${name}"><div class="venueTop"><b>${name}</b><span>${cur?'開催情報あり':'情報待ち'}</span></div><div class="venueMeta"><strong>${rn?rn+'R':'--'}</strong><small>${dl||'--'}</small></div></button>`}).join('');$$('.venue').forEach(b=>b.onclick=()=>openVenue(b.dataset.v));const targets=VENUES.map(v=>classifyVenueRace(venueRaces(v))).filter(Boolean).sort((a,b)=>(+parseDeadline(a)||Infinity)-(+parseDeadline(b)||Infinity));const n=targets[0];$('#nextRace').textContent=n?`次の対象：${venueName(n)} ${raceNo(n)}R　締切 ${deadline(n)||'--'}`:'本日の対象レースを確認中';}
function openVenue(name){currentVenue=name;const list=venueRaces(name);const current=classifyVenueRace(list);$('#raceHeader').innerHTML=`<div class="raceTitle"><div><div class="eyebrow">RACE LIST</div><h2>${name}</h2></div><div class="currentBadge">直近のみ判定</div></div>`;$('#venueWeather').textContent=current?(current.weather||current.condition||''):'';$('#raceList').innerHTML=list.length?list.map(r=>{const rn=raceNo(r);let status='未判定',cls='pending',click='';if(current&&r===current){const s=decision(r);status=stateText(s);cls=s;click='data-open="1"'}else if(current&&isPast(r,current)){status='終了';cls='done'}return `<button class="raceRow ${cls}" ${click} data-race="${rn}"><div><b>${rn||'--'}R</b><small>${deadline(r)||'--'}</small></div><span>${status}</span></button>`}).join(''):'<div class="empty">本日のレース情報はまだありません。</div>';$$('.raceRow[data-open="1"]').forEach(b=>b.onclick=()=>openDetail(name,+b.dataset.race));show('raceSection')}
function groupedPicks(r){const src=Array.isArray(r?.picks)?r.picks:Array.isArray(r?.bets)?r.bets:[];const out={main:[],mid:[],long:[]};for(const p of src){const o=+(p.odds??p.expected_odds??0);if(o>=60)out.long.push(p);else if(o>=20)out.mid.push(p);else out.main.push(p)}return out}
function pickRows(arr){return arr.length?arr.map(p=>`<div class="pick"><b>${p.combination||p.bet||p.combo||'--'}</b><span>${Number.isFinite(+(p.odds??p.expected_odds))?`${+(p.odds??p.expected_odds)}倍`:''}</span><strong>${yen(p.stake_yen??p.amount??p.stake)}</strong></div>`).join(''):'<div class="empty small">確定データなし</div>'}
function infoItem(label,value){return `<div class="infoItem"><span>${label}</span><b>${value??'--'}</b></div>`}
function openDetail(name,rn){const r=venueRaces(name).find(x=>raceNo(x)===rn);if(!r)return;const s=decision(r),score=r?.score??r?.value_score??r?.confidence??'--',groups=groupedPicks(r);$('#detailStatus').textContent=stateText(s);$('#detailBody').innerHTML=`<div class="detailHero"><div><div class="eyebrow">${name} ${rn}R</div><h2>${stateText(s)}</h2><p>${r?.comment||r?.ai_comment||r?.reason||'直前データをもとに判定します。'}</p></div><div class="score"><span>買う価値</span><b>${score}</b></div></div><div class="tabs"><button class="tab active" data-tab="prediction">予想</button><button class="tab" data-tab="late">直前情報</button><button class="tab" data-tab="analysis">データ分析</button></div><div class="tabPanel active" id="prediction"><div class="infoGrid">${infoItem('締切',deadline(r)||'--')}${infoItem('投資',yen(r?.stake_total_yen??r?.stake))}${infoItem('採用理論',r?.theory||r?.logic_name||'--')}</div><div class="betGroups"><details open><summary>本命 <span>${groups.main.length}点</span></summary>${pickRows(groups.main)}</details><details><summary>中穴 <span>${groups.mid.length}点</span></summary>${pickRows(groups.mid)}</details><details><summary>穴 <span>${groups.long.length}点</span></summary>${pickRows(groups.long)}</details></div></div><div class="tabPanel" id="late"><div class="infoGrid">${infoItem('展示タイム',r?.exhibition_time||r?.tenji_time)}${infoItem('ST',r?.st||r?.start_timing)}${infoItem('進入',r?.entry||r?.course_entry)}${infoItem('風速',r?.wind_speed?`${r.wind_speed}m`:r?.wind)}${infoItem('風向',r?.wind_direction)}${infoItem('波高',r?.wave_height?`${r.wave_height}cm`:r?.wave)}${infoItem('天候',r?.weather)}${infoItem('直前オッズ',r?.odds_summary||r?.odds)}</div></div><div class="tabPanel" id="analysis"><div class="analysisBox">${r?.analysis||r?.analysis_text||r?.reason||'分析データは取得できた項目から表示します。'}</div><div class="infoGrid">${infoItem('モーター',r?.motor||r?.motor_no)}${infoItem('コース傾向',r?.course_trend)}${infoItem('場クセ',r?.venue_trend)}${infoItem('当日流れ',r?.day_flow)}</div></div>`;$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tabPanel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.tab).classList.add('active')});show('detail')}
function show(id){['venueSection','raceSection','detail'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));scrollTo({top:0,behavior:'smooth'})}
async function load(){const logs=[];try{const h=await api('/api/health');$('#health').textContent=h.ok?'SYSTEM ONLINE':'API待機';$('#health').className='pill '+(h.ok?'ok':'ng');logs.push(`API: ${h.ok?'正常':'待機'}`)}catch{$('#health').textContent='API待機';$('#health').className='pill ng';logs.push('API: 接続待機')}try{const d=await api('/api/live');races=rows(d);logs.push(`本日データ: ${races.length}件`)}catch{races=[];logs.push('本日データ: 取得待機')}try{const p=await api('/api/performance');const x=Array.isArray(p?.data)?p.data[0]:p?.data||p;$('#hitRate').textContent=pct(x?.hit_rate??x?.hitRate);$('#roi').textContent=pct(x?.roi??x?.recovery_rate);const pr=+(x?.profit_yen??x?.profit);$('#profit').textContent=Number.isFinite(pr)?yen(pr):'--';$('#profit').className=Number.isFinite(pr)?(pr>=0?'plus':'minus'):''}catch{}renderVenues();$('#statusLog').textContent=logs.join('\n')+'\n未来レース：未判定 / 直近レースのみ判定';}
$('#reload').onclick=load;$('#backToVenues').onclick=()=>show('venueSection');$('#backToRaces').onclick=()=>openVenue(currentVenue);$$('.bottomNav button').forEach(b=>b.onclick=()=>{if(b.dataset.go==='venues')show('venueSection');else if(b.dataset.go==='performance')document.querySelector('.stats')?.scrollIntoView({behavior:'smooth'});else scrollTo({top:0,behavior:'smooth'})});load();