export const OBPE_POLICY={max_race_stake_yen:5000,unit_yen:100,risk_base_yen:20000,min_conservative_ev:0.10,odds_buffer:0.95};
const finite=v=>Number.isFinite(Number(v));
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,Number(x)||0));
export function trifectaTickets(){const out=[];for(let a=1;a<=6;a++)for(let b=1;b<=6;b++)for(let c=1;c<=6;c++)if(a!==b&&a!==c&&b!==c)out.push(`${a}-${b}-${c}`);return out}
export function normalizeDistribution(input={}){const tickets=trifectaTickets(),raw=tickets.map(t=>Math.max(0,Number(input[t]||0))),sum=raw.reduce((a,b)=>a+b,0);if(!(sum>0))throw new Error('distribution_has_no_mass');return Object.fromEntries(tickets.map((t,i)=>[t,raw[i]/sum]))}
export function validateDistribution(dist,tolerance=1e-9){const tickets=trifectaTickets();if(tickets.some(t=>!finite(dist?.[t])||Number(dist[t])<0))return false;const sum=tickets.reduce((s,t)=>s+Number(dist[t]),0);return Math.abs(sum-1)<=tolerance}
export function marketProbabilities(odds={}){const rows=Object.entries(odds).filter(([t,o])=>/^\d-\d-\d$/.test(t)&&new Set(t.split('-')).size===3&&Number(o)>1).map(([t,o])=>[t,Number(o),1/Number(o)]),sum=rows.reduce((s,x)=>s+x[2],0);return Object.fromEntries(rows.map(([t,,inv])=>[t,inv/sum]))}
export function conservativeProbability(p,uncertainty){return Math.max(0,Number(p||0)*(1-0.45*clamp(uncertainty)))}
export function candidateRows(dist,odds,uncertainty,policy=OBPE_POLICY){const market=marketProbabilities(odds);return Object.entries(dist).map(([ticket,p])=>{const o=Number(odds[ticket]);if(!(o>1)||!finite(market[ticket]))return null;const cp=conservativeProbability(p,uncertainty),buffered=o*policy.odds_buffer,ev=cp*buffered-1,edge=Number(p)-Number(market[ticket]);return{ticket,model_probability:Number(p),conservative_probability:cp,odds:o,buffered_odds:buffered,market_probability:Number(market[ticket]),edge,conservative_ev:ev}}).filter(Boolean).sort((a,b)=>b.conservative_ev-a.conservative_ev)}
export function logWealthObjective(rows,stakes,policy=OBPE_POLICY){const S=stakes.reduce((a,b)=>a+b,0),base=policy.risk_base_yen-S;if(base<=0)return-Infinity;const selectedP=rows.reduce((s,x,i)=>s+(stakes[i]>0?x.conservative_probability:0),0),otherP=Math.max(0,1-selectedP);let value=otherP*Math.log(base);for(let i=0;i<rows.length;i++){if(stakes[i]<=0)continue;const wealth=base+stakes[i]*rows[i].buffered_odds;if(wealth<=0)return-Infinity;value+=rows[i].conservative_probability*Math.log(wealth)}return value}
export function allocateMutuallyExclusive(rows,policy=OBPE_POLICY){const eligible=rows.filter(x=>x.conservative_ev>policy.min_conservative_ev&&x.edge>0).slice(0,18),stakes=Array(eligible.length).fill(0);if(!eligible.length)return{bets:[],total:0};let current=logWealthObjective(eligible,stakes,policy);while(stakes.reduce((a,b)=>a+b,0)+policy.unit_yen<=policy.max_race_stake_yen){let best=-1,bestValue=current;for(let i=0;i<eligible.length;i++){const trial=stakes.slice();trial[i]+=policy.unit_yen;const v=logWealthObjective(eligible,trial,policy);if(v>bestValue+1e-10){best=i;bestValue=v}}if(best<0)break;stakes[best]+=policy.unit_yen;current=bestValue}const bets=eligible.map((x,i)=>({...x,stake_yen:stakes[i]})).filter(x=>x.stake_yen>0);return{bets,total:bets.reduce((s,x)=>s+x.stake_yen,0)}}
