import base from './worker_customer.js';

const SUPABASE_URL='https://imhzjlxbnovjvqlyawmg.supabase.co';
const SUPABASE_KEY='sb_publishable_-VcTpMDA4uaDfKmqxYw-0Q_v2vAZe7V';
const MEMBERSHIP_API=`${SUPABASE_URL}/functions/v1/one-boat-membership-api`;
const ACCESS_COOKIE='ob_at';
const REFRESH_COOKIE='ob_rt';

function json(data,status=200,cookies=[]){const h=new Headers({'content-type':'application/json;charset=utf-8','cache-control':'no-store, max-age=0','x-content-type-options':'nosniff'});for(const c of cookies)h.append('set-cookie',c);return new Response(JSON.stringify(data),{status,headers:h})}
function redirect(url,status=302,cookies=[]){const h=new Headers({location:url,'cache-control':'no-store'});for(const c of cookies)h.append('set-cookie',c);return new Response(null,{status,headers:h})}
function cookieMap(request){const out={};for(const part of String(request.headers.get('cookie')||'').split(';')){const i=part.indexOf('=');if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function authCookies(d){const max=Number(d?.expires_in||3600);return [`${ACCESS_COOKIE}=${encodeURIComponent(d.access_token)}; Path=/; Max-Age=${Math.max(60,max)}; HttpOnly; Secure; SameSite=Lax`,`${REFRESH_COOKIE}=${encodeURIComponent(d.refresh_token)}; Path=/; Max-Age=2592000; HttpOnly; Secure; SameSite=Lax`]}
function clearCookies(){return [`${ACCESS_COOKIE}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax`,`${REFRESH_COOKIE}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Lax`]}
function sameOrigin(request){const origin=request.headers.get('origin');return !origin||origin===new URL(request.url).origin}
async function bodyJson(request){try{return await request.json()}catch{return{}}}
async function sb(path,{method='GET',token,body}={}){const h=new Headers({'apikey':SUPABASE_KEY,'accept':'application/json'});if(token)h.set('authorization',`Bearer ${token}`);if(body!==undefined)h.set('content-type','application/json');return fetch(`${SUPABASE_URL}${path}`,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'})}
async function authUser(token){if(!token)return null;const r=await sb('/auth/v1/user',{token});if(!r.ok)return null;return r.json()}
async function refreshSession(refreshToken){if(!refreshToken)return null;const r=await sb('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:refreshToken}});if(!r.ok)return null;const d=await r.json();return d?.access_token&&d?.refresh_token?d:null}
async function entitlement(token){try{const r=await fetch(`${MEMBERSHIP_API}?action=me`,{headers:{authorization:`Bearer ${token}`,accept:'application/json'},cache:'no-store'});if(!r.ok)return null;const d=await r.json().catch(()=>null);return d?.ok?d:null}catch{return null}}
function unavailableEntitlement(){return{effective_plan:'UNKNOWN',has_paid_access:false,access_expires_at:null,stored_status:'unavailable',cancel_at_period_end:false,eligibility_confirmed:false}}
async function resolveSession(request){const c=cookieMap(request);let token=c[ACCESS_COOKIE]||'',user=await authUser(token),cookies=[];if(!user&&c[REFRESH_COOKIE]){const fresh=await refreshSession(c[REFRESH_COOKIE]);if(fresh){token=fresh.access_token;cookies=authCookies(fresh);user=await authUser(token)}}if(!user)return{ok:false,cookies:clearCookies()};const ent=await entitlement(token);return{ok:true,token,user:{id:user.id,email:user.email||''},ent:ent||unavailableEntitlement(),entitlement_unavailable:!ent,cookies}}
function publicSession(s){if(!s.ok)return{ok:true,logged_in:false,plan:'guest',paid_access:false};const e=s.ent||unavailableEntitlement();const plan=e.effective_plan==='DAY_PASS'?'day_pass':e.effective_plan==='CLUB_MONTHLY'?'club_monthly':e.effective_plan==='FREE'?'free':'unknown';return{ok:true,logged_in:true,email:s.user.email,plan,status:e.stored_status||'unavailable',access_expires_at:e.access_expires_at||null,next_billing_at:plan==='club_monthly'?(e.access_expires_at||null):null,cancel_at_period_end:!!e.cancel_at_period_end,age_20_confirmed:!!e.eligibility_confirmed,paid_access:e.has_paid_access===true,entitlement_available:!s.entitlement_unavailable}}
async function signup(request){if(!sameOrigin(request))return json({ok:false,error:'origin'},403);const b=await bodyJson(request),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(!email||password.length<8)return json({ok:false,error:'invalid_input',message:'メールアドレスと8文字以上のパスワードを入力してください。'},400);if(b.age20!==true||b.terms!==true||b.privacy!==true)return json({ok:false,error:'consent_required',message:'20歳以上の確認と規約・プライバシーポリシーへの同意が必要です。'},400);const r=await sb('/auth/v1/signup',{method:'POST',body:{email,password,data:{age_20_confirmed:true,accepted_at:new Date().toISOString()}}});const d=await r.json().catch(()=>({}));if(!r.ok)return json({ok:false,error:'signup_failed',message:d?.msg||d?.message||'登録できませんでした。'},r.status);if(d.access_token&&d.refresh_token)return json({ok:true,logged_in:true,confirmation_required:false},200,authCookies(d));return json({ok:true,logged_in:false,confirmation_required:true,message:'確認メールを送信しました。メール内のリンクから登録を完了してください。'})}
async function login(request){if(!sameOrigin(request))return json({ok:false,error:'origin'},403);const b=await bodyJson(request),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');const r=await sb('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});const d=await r.json().catch(()=>({}));if(!r.ok||!d.access_token)return json({ok:false,error:'login_failed',message:'メールアドレスまたはパスワードを確認してください。'},401);return json({ok:true},200,authCookies(d))}
async function logout(request){if(!sameOrigin(request))return json({ok:false,error:'origin'},403);const c=cookieMap(request);if(c[ACCESS_COOKIE])await sb('/auth/v1/logout',{method:'POST',token:c[ACCESS_COOKIE]}).catch(()=>{});return json({ok:true},200,clearCookies())}
async function session(request){const s=await resolveSession(request);return json(publicSession(s),200,s.cookies||[])}
async function billing(request,action){if(!sameOrigin(request))return json({ok:false,error:'origin'},403);const s=await resolveSession(request);if(!s.ok)return json({ok:false,error:'login_required',message:'ログインが必要です。'},401,s.cookies||[]);if(s.entitlement_unavailable)return json({ok:false,error:'entitlement_unavailable',message:'会員状態を確認できないため、安全のため購入・解約操作を停止しています。'},503,s.cookies||[]);if(!s.ent?.eligibility_confirmed)return json({ok:false,error:'age_confirmation_required',message:'20歳以上の確認と規約同意が必要です。'},403,s.cookies||[]);const body=await bodyJson(request);if(action==='checkout'&&!['day_pass','club_monthly'].includes(String(body.plan||'')))return json({ok:false,error:'invalid_plan'},400,s.cookies||[]);const r=await fetch(`${MEMBERSHIP_API}?action=${encodeURIComponent(action)}`,{method:'POST',headers:{authorization:`Bearer ${s.token}`,'content-type':'application/json',accept:'application/json'},body:JSON.stringify(action==='checkout'?{plan:String(body.plan)}:{}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok){const pending=d?.error==='billing_not_configured'||d?.error==='stripe_not_configured';const message=pending?'決済システムの最終接続中です。購入・解約はまだ確定しません。':action==='cancel'?'解約処理を完了できませんでした。時間をおいて再度お試しください。':'決済サービスを利用できません。';return json({ok:false,error:d?.error||'billing_unavailable',message},r.status,s.cookies||[])}return json(d,200,s.cookies||[])}
async function protectedPage(request,env){const s=await resolveSession(request),baseUrl=new URL(request.url).origin;if(!s.ok)return redirect(`${baseUrl}/login.html?next=${encodeURIComponent('/premium.html')}`,302,s.cookies||[]);if(s.entitlement_unavailable||s.ent?.has_paid_access!==true)return redirect(`${baseUrl}/club.html?locked=1`,302,s.cookies||[]);const u=new URL(request.url);u.pathname='/premium.html';u.search='';const r=await env.ASSETS.fetch(new Request(u,request));const h=new Headers(r.headers);h.set('cache-control','private,no-store,max-age=0');h.set('x-robots-tag','noindex,nofollow');for(const c of s.cookies||[])h.append('set-cookie',c);return new Response(r.body,{status:r.status,headers:h})}

export default{async fetch(request,env,ctx){const u=new URL(request.url);try{if(u.pathname==='/api/auth/signup'&&request.method==='POST')return signup(request);if(u.pathname==='/api/auth/login'&&request.method==='POST')return login(request);if(u.pathname==='/api/auth/logout'&&request.method==='POST')return logout(request);if((u.pathname==='/api/auth/session'||u.pathname==='/api/member/session')&&request.method==='GET')return session(request);if(u.pathname==='/api/member/checkout-intent'&&request.method==='POST')return billing(request,'checkout');if(u.pathname==='/api/member/billing-portal'&&request.method==='POST')return billing(request,'portal');if(u.pathname==='/api/member/cancel-subscription'&&request.method==='POST')return billing(request,'cancel');if(u.pathname==='/premium.html')return protectedPage(request,env);return base.fetch(request,env,ctx)}catch{return json({ok:false,error:'member_service_unavailable',message:'会員サービスを一時的に利用できません。'},503)}}};
