import {DEFAULT_POLICY,CONFIDENCE_AXES,evaluateRace,aggregateBacktest,walkForward} from './engine_v51.js';
const UPSTREAM='https://vtgswxrzklwynpvifbef.supabase.co/functions/v1';
const ROUTES={'/api/live':'one-boat-live-api','/api/detail':'boat-ai-race-detail','/api/performance':'boat-ai-performance','/api/patterns':'one-boat-venue-patterns','/api/schedule':'boat-ai-schedule'};
const TTL={'/api/live':30,'/api/detail':20,'/api/performance':120,'/api/patterns':3600,'/api/schedule':300};
function json(x,status=200,cache='no-store'){return new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':cache}})}
async function upstream(request,fn,path,ctx,suffix=''){const src=new URL(request.url),target=new URL(`${UPSTREAM}/${fn}${suffix}`);target.search=src.search;const key=new Request(src.toString(),{method:'GET'});try{if(request.method==='GET'){const cached=await caches.default.match(key);if(cached)return cached}}catch{}const headers=new Headers(request.headers);['host','cookie','origin','referer'].forEach(h=>headers.delete(h));const init={method:request.method,headers,redirect:'follow'};if(!['GET','HEAD'].includes(request.method))init.body=request.body;try{const r=await fetch(target,init),h=new Headers(r.headers);h.delete('set-cookie');h.set('cache-control',`public,max-age=${TTL[path]||30}`);const out=new Response(r.body,{status:r.status,headers:h});if(request.method==='GET'&&r.ok)ctx.waitUntil(Promise.resolve().then(()=>caches.default.put(key,out.clone())).catch(()=>{}));return out}catch{return json({ok:false,error:'upstream_unavailable'},502)}}
function jstYmd(){const d=new Date(Date.now()+9*3600*1000);return d.toISOString().slice(0,10).replaceAll('-','')}
async function official(u,ctx){const raw=(u.searchParams.get('date')||'').replaceAll('-','');if(!/^\d{8}$/.test(raw))return json({ok:false,error:'date_required'},400);const today=jstYmd(),target=raw===today?'https://boatraceopenapi.github.io/api/v1/today.json':`https://boatraceopenapi.github.io/api/v1/${raw.slice(0,4)}/${raw}.json`,key=new Request(`${u.origin}/api/official?date=${raw}&v=51`);try{const cached=await caches.default.match(key);if(cached)return cached}catch{}try{const r=await fetch(target,{headers:{accept:'application/json','user-agent':'ONE-BOAT/1.0'}});if(!r.ok)return json({ok:false,error:`official_${r.status}`},502);const parsed=await r.json(),out=json(parsed,200,'public,max-age=60');ctx.waitUntil(Promise.resolve().then(()=>caches.default.put(key,out.clone())).catch(()=>{}));return out}catch{return json({ok:false,error:'official_unavailable'},502)}}
function plainHtml(html){return String(html||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&deg;/gi,'°').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim()}
function parseOfficialWeather(html){const text=plainHtml(html),tm=text.match(/気温\s*([+-]?\d+(?:\.\d+)?)\s*℃/),wm=text.match(/風速\s*([+-]?\d+(?:\.\d+)?)\s*m/),wt=text.match(/水温\s*([+-]?\d+(?:\.\d+)?)\s*℃/),wave=text.match(/波高\s*([+-]?\d+(?:\.\d+)?)\s*cm/);let weather=null;if(tm){const tail=text.slice(tm.index+tm[0].length,tm.index+tm[0].length+40),m=tail.match(/^\s*(晴れ|晴|曇り|曇|雨|雪|霧|小雨|弱雨|強雨|雷雨)/);if(m)weather=m[1]}if(!weather){const m=text.match(/(?:天候|天気)\s*(晴れ|晴|曇り|曇|雨|雪|霧|小雨|弱雨|強雨|雷雨)/);if(m)weather=m[1]}return {weather,temperature:tm?Number(tm[1]):null,wind_speed:wm?Number(wm[1]):null,water_temperature:wt?Number(wt[1]):null,wave_height:wave?Number(wave[1]):null}}
async function officialWeather(u,ctx){const raw=(u.searchParams.get('date')||jstYmd()).replaceAll('-',''),jcd=String(u.searchParams.get('jcd')||'').padStart(2,'0'),rno=Math.max(1,Math.min(12,Number(u.searchParams.get('rno')||1)));if(!/^\d{8}$/.test(raw)||!/^(0[1-9]|1\d|2[0-4])$/.test(jcd))return json({ok:false,error:'bad_params'},400);const key=new Request(`${u.origin}/api/official-weather?date=${raw}&jcd=${jcd}&rno=${rno}&v=2`);try{const cached=await caches.default.match(key);if(cached)return cached}catch{}let last=null;for(const n of [rno,Math.max(1,rno-1)]){try{const target=`https://www.boatrace.jp/owsp/sp/race/beforeinfo?hd=${raw}&jcd=${jcd}&rno=${n}`,r=await fetch(target,{headers:{accept:'text/html,*/*','user-agent':'Mozilla/5.0 ONE-BOAT/1.0'}});if(!r.ok)continue;const parsed=parseOfficialWeather(await r.text());last={ok:true,source:'BOAT RACE official beforeinfo',source_race:n,...parsed};if(parsed.weather||parsed.temperature!==null||parsed.wind_speed!==null)break}catch{}}if(!last)last={ok:false,error:'official_weather_unavailable',weather:null,temperature:null,wind_speed:null,water_temperature:null,wave_height:null};const out=json(last,200,'public,max-age=90');ctx.waitUntil(Promise.resolve().then(()=>caches.default.put(key,out.clone())).catch(()=>{}));return out}
async function body(request){try{return await request.json()}catch{return null}}
function deepFind(o,keys,depth=0){if(o===null||o===undefined||depth>6)return undefined;if(typeof o!=='object')return undefined;for(const k of keys)if(o[k]!==undefined&&o[k]!==null)return o[k];for(const k of Object.keys(o)){const v=o[k];if(v&&typeof v==='object'){const z=deepFind(v,keys,depth+1);if(z!==undefined)return z}}return undefined}
function payloadOf(raw){if(raw&&raw.data&&typeof raw.data==='object'&&!Array.isArray(raw.data))return raw.data;if(raw&&raw.result&&typeof raw.result==='object'&&!Array.isArray(raw.result))return raw.result;return raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{}}
function mergePayload(raw,merged){if(raw&&raw.data&&typeof raw.data==='object'&&!Array.isArray(raw.data))return {...raw,data:merged};if(raw&&raw.result&&typeof raw.result==='object'&&!Array.isArray(raw.result))return {...raw,result:merged};return {...(raw&&typeof raw==='object'?raw:{}),...merged}}
function num(v,fallback=0){const n=Number(v);return Number.isFinite(n)?n:fallback}
function pickAmount(x){return num(x?.stake_yen??x?.amount??x?.stake,0)}
function capPicks(picks,target){target=Math.floor(Math.max(0,Math.min(5000,num(target,0)))/100)*100;if(target<100)return[];let xs=(Array.isArray(picks)?picks:[]).slice(0,6).map(x=>({...x}));if(!xs.length)return[];const allowed=Math.min(xs.length,Math.floor(target/100));xs=xs.slice(0,allowed);const weights=xs.map(x=>Math.max(0,pickAmount(x)));const weightSum=weights.reduce((a,b)=>a+b,0);const safeWeights=weightSum>0?weights:xs.map(()=>1);const safeSum=safeWeights.reduce((a,b)=>a+b,0);let amounts=xs.map(()=>100),remaining=target-xs.length*100;if(remaining>0){const desired=safeWeights.map(w=>remaining*w/safeSum);for(let i=0;i<amounts.length;i++){const add=Math.floor(desired[i]/100)*100;amounts[i]+=add;remaining-=add}const order=safeWeights.map((w,i)=>({w,i})).sort((a,b)=>b.w-a.w);let oi=0;while(remaining>=100&&order.length){amounts[order[oi%order.length].i]+=100;remaining-=100;oi++}}return xs.map((x,i)=>({...x,stake_yen:amounts[i],amount:amounts[i],stake:amounts[i]}))}
function raceNoFrom(src,p){const direct=deepFind(p,['race_no','race']);if(Number.isFinite(Number(direct)))return Number(direct);const code=String(src.searchParams.get('race_code')||'');const tail=code.match(/(\d{2})$/);return tail?Number(tail[1]):0}
function buildRaceInput(src,p,picks,stake){const summary=p.summary_scores&&typeof p.summary_scores==='object'?p.summary_scores:{};const confidence=deepFind(p,['confidence_components','confidence_breakdown']);return {
  score:deepFind(p,['value_score','score'])??summary.value_score,
  value_score:summary.value_score??deepFind(p,['value_score']),
  confidence:summary.confidence_score??deepFind(p,['confidence_score','confidence']),
  confidence_components:confidence&&typeof confidence==='object'&&!Array.isArray(confidence)?confidence:undefined,
  stake_total_yen:stake,
  points:Math.min(6,Math.max(1,picks.length||num(deepFind(p,['points']),DEFAULT_POLICY.base_points))),
  odds:deepFind(p,['expected_odds','odds','target_odds','recommended_odds']),
  expected_value:deepFind(p,['expected_value','ev']),
  missing_data_count:deepFind(p,['missing_data_count'])??0,
  theory_scores:deepFind(p,['theory_scores','theories']),
  theory_sample:deepFind(p,['theory_sample','sample']),
  theory_roi:deepFind(p,['theory_roi','roi']),
  hole_score:deepFind(p,['hole_score','longshot_score']),
  daily_hole_enter_count:deepFind(p,['daily_hole_enter_count']),
  venue_recent_results:deepFind(p,['venue_recent_results','recent_venue_results','today_results']),
  current_theory:deepFind(p,['current_theory','strategy','theory']),
  race_no:raceNoFrom(src,p),
  wind_direction:deepFind(p,['wind_direction','wind_dir']),
  wind_speed:deepFind(p,['wind_speed','wind_speed_mps']),
  wind_history_14d:deepFind(p,['wind_history_14d','wind14d_history','similar_wind_results']),
  wind_match_score:deepFind(p,['wind14d_in_win_rate','boat1_wind_win_rate','wind_in_win_rate']),
  wind14d_sample:deepFind(p,['wind14d_sample']),
  water_type:deepFind(p,['water_type','venue_water_type','water_quality']),
  tide_score:deepFind(p,['tide_score','tide_fit_score']),
  temperature_motor_score:deepFind(p,['temperature_motor_score','temp_water_score','temperature_water_score']),
  previous_motor_user_score:deepFind(p,['previous_motor_user_score','previous_user_motor_score']),
  motor_player_fit_score:deepFind(p,['motor_player_fit_score','motor_racer_fit_score']),
  second_third_match_score:deepFind(p,['second_third_match_score','tie_candidate_score'])
}}
async function livePredict(request){const src=new URL(request.url),target=new URL(`${UPSTREAM}/one-boat-live-api/predict`);target.search=src.search;const headers=new Headers(request.headers);['host','cookie','origin','referer'].forEach(h=>headers.delete(h));const init={method:request.method,headers,redirect:'follow'};if(!['GET','HEAD'].includes(request.method))init.body=request.body;let r;try{r=await fetch(target,init)}catch{return json({ok:false,error:'upstream_unavailable'},502)}const text=await r.text();let raw;try{raw=JSON.parse(text)}catch{return new Response(text,{status:r.status,headers:{'content-type':r.headers.get('content-type')||'text/plain;charset=utf-8','cache-control':'no-store'}})}if(!r.ok)return json(raw,r.status,'no-store');const p=payloadOf(raw);const picks=Array.isArray(p.production_picks)?p.production_picks:[];let stake=num(p.stake_total_yen??p.stake,0);if(stake<=0&&picks.length)stake=picks.reduce((s,x)=>s+pickAmount(x),0);const raceInput=buildRaceInput(src,p,picks,stake);const history={sample:num(raceInput.theory_sample,0),roi:num(raceInput.theory_roi,0),daily_hole_enter_count:num(raceInput.daily_hole_enter_count,0)};const evaluated=evaluateRace(raceInput,DEFAULT_POLICY,history);const upstreamAllowed=p.purchase_allowed===true;const final=src.searchParams.get('final')==='1';const candidateEnter=upstreamAllowed&&picks.length>0&&evaluated.decision==='ENTER'&&evaluated.stake_total_yen>0;const finalPicks=candidateEnter?capPicks(picks,evaluated.stake_total_yen):[];const finalStake=finalPicks.reduce((s,x)=>s+pickAmount(x),0);const enter=candidateEnter&&finalPicks.length>0&&finalStake>0&&finalStake<=5000&&finalStake%100===0;const decision=enter?'ENTER':final?'SKIP':(evaluated.decision==='SKIP'?'SKIP':'WATCH');const merged={...p,
  purchase_allowed:enter,
  decision,
  stake_total_yen:enter?finalStake:0,
  production_picks:enter?finalPicks:[],
  summary_scores:{...(p.summary_scores||{}),value_score:evaluated.value_score,confidence_score:evaluated.confidence_score},
  confidence_breakdown:evaluated.breakdown,
  prediction_reasons:evaluated.reasons,
  category:evaluated.category,
  strategy:evaluated.strategy,
  selected_theory:evaluated.selected_theory,
  day_flow_theory:evaluated.day_flow_theory,
  initial_theory:evaluated.initial_theory,
  auxiliary_adjustment:evaluated.auxiliary_adjustment,
  auxiliary_reasons:evaluated.auxiliary_reasons,
  monitor:evaluated.monitor,
  local_rule_reason:enter?evaluated.reason:(upstreamAllowed?evaluated.reason:(p.reason||p.decision_reason||'上流予想未確定')),
  local_engine:'ONE BOAT V5.1'
};return json(mergePayload(raw,merged),200,final?'no-store':'public,max-age=15')}
async function assetResponse(request,env){if(!env?.ASSETS?.fetch)return null;const res=await env.ASSETS.fetch(request),u=new URL(request.url),ct=res.headers.get('content-type')||'';if(res.ok&&(u.pathname==='/'||u.pathname==='/index.html')&&ct.includes('text/html')){return new HTMLRewriter().on('body',{element(el){el.append('<script src="/race-screen-enhancer.js?v=61bc20d8"></script>',{html:true})}}).transform(res)}return res}
export default{async fetch(request,env,ctx){try{const u=new URL(request.url);if(u.pathname==='/api/health')return json({ok:true,service:'ONE BOAT',version:'2026.09-v5.1',architecture:'edge-cache-first',engine:'7axis+auxiliary-context+live-post-guard',max_stake_yen:DEFAULT_POLICY.max_stake_yen,final_lock_minutes:DEFAULT_POLICY.finalize_minutes});if(u.pathname==='/api/config')return json({ok:true,...DEFAULT_POLICY,confidence_axes:CONFIDENCE_AXES,final_lock_minutes:DEFAULT_POLICY.finalize_minutes,enter_rule:'upstream purchase_allowed && picks>0 && local value>=70 && ROI guard && stake>0',confidence_rule:'7-axis confidence is shadow-tracked; auxiliary signals may adjust value but one signal alone cannot create ENTER',auxiliary_rule:'wind14d+tide(sea/brackish only)+temperature/water+previous motor user+motor-player fit; positive adjustment requires 2 supportive signals'});if(u.pathname==='/api/official')return official(u,ctx);if(u.pathname==='/api/official-weather')return officialWeather(u,ctx);if(u.pathname==='/api/evaluate'&&request.method==='POST'){const x=await body(request);if(!x?.race)return json({ok:false,error:'race_required'},400);return json({ok:true,result:evaluateRace(x.race,x.policy||DEFAULT_POLICY,x.history||{})})}if(u.pathname==='/api/backtest'&&request.method==='POST'){const x=await body(request),rows=Array.isArray(x?.rows)?x.rows:[];return json({ok:true,summary:aggregateBacktest(rows),walk_forward:walkForward(rows,Number(x?.train_ratio)||.7),warning:rows.length?'':'no historical rows supplied'})}if(u.pathname==='/api/live/predict')return livePredict(request);if(u.pathname.startsWith('/api/live/'))return upstream(request,'one-boat-live-api','/api/live',ctx,u.pathname.slice('/api/live'.length));const fn=ROUTES[u.pathname];if(fn)return upstream(request,fn,u.pathname,ctx);const asset=await assetResponse(request,env);if(asset)return asset;return json({ok:false,error:'assets_binding_missing'},503)}catch(e){return json({ok:false,error:'worker_runtime_error',message:String(e?.message||e)},500)}}};