const SITE_API='https://imhzjlxbnovjvqlyawmg.supabase.co/functions/v1/one-boat-site-api';
const LIVE_FEED='https://imhzjlxbnovjvqlyawmg.supabase.co/functions/v1/one-boat-live-feed';
const SETTLE_API='https://imhzjlxbnovjvqlyawmg.supabase.co/functions/v1/one-boat-obpe-settle';
const HISTORY_API='https://imhzjlxbnovjvqlyawmg.supabase.co/functions/v1/one-boat-obpe-history';
const MODEL_VERSION='OBPE-1.0.2';
const TTL={predict:0,detail:20,performance:30,patterns:120,schedule:30};
function json(x,status=200,cache='no-store'){return new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':cache}})}
function jstYmd(){return new Date(Date.now()+9*3600*1000).toISOString().slice(0,10).replaceAll('-','')}
function jstDate(){const x=jstYmd();return `${x.slice(0,4)}-${x.slice(4,6)}-${x.slice(6,8)}`}
async function proxy(request,suffix,ttl=20){const src=new URL(request.url),target=new URL(`${SITE_API}/${suffix}`);target.search=src.search;const headers=new Headers(request.headers);['host','cookie','origin','referer'].forEach(h=>headers.delete(h));const init={method:request.method,headers,redirect:'follow'};if(!['GET','HEAD'].includes(request.method))init.body=request.body;try{const r=await fetch(target,init),h=new Headers(r.headers);h.delete('set-cookie');h.set('cache-control',ttl>0&&request.method==='GET'?`public,max-age=${ttl}`:'no-store');return new Response(r.body,{status:r.status,headers:h})}catch{return json({ok:false,error:'site_api_unavailable'},502)}}
async function predictProxy(request,ctx){const src=new URL(request.url),target=new URL(`${SITE_API}/predict`);target.search=src.search;const headers=new Headers(request.headers);['host','cookie','origin','referer'].forEach(h=>headers.delete(h));try{const r=await fetch(target,{method:'GET',headers,redirect:'follow',cache:'no-store'}),text=await r.text(),h=new Headers(r.headers);h.delete('set-cookie');h.set('cache-control','no-store');if(r.ok&&src.searchParams.get('final')==='1'){try{const p=JSON.parse(text),raceCode=src.searchParams.get('race_code')||'';if(/^\d{12}$/.test(raceCode)&&p&&p.locked===true){ctx.waitUntil(fetch(HISTORY_API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({race_code:raceCode,prediction:p,final:true})}).then(x=>x.arrayBuffer()).catch(()=>{}))}}catch{}}return new Response(text,{status:r.status,headers:h})}catch{return json({ok:false,error:'site_api_unavailable'},502)}}
async function historyProxy(request){const src=new URL(request.url),target=new URL(HISTORY_API);target.search=src.search;try{const r=await fetch(target,{headers:{accept:'application/json'},cache:'no-store'});return new Response(r.body,{status:r.status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store'}})}catch{return json({ok:false,error:'history_unavailable'},502)}}
async function liveFeed(request){const src=new URL(request.url),path=src.pathname.slice('/api/live/'.length),target=new URL(LIVE_FEED);target.searchParams.set('path',path);for(const[k,v]of src.searchParams)target.searchParams.set(k,v);try{const r=await fetch(target,{headers:{accept:'application/json'}});return new Response(r.body,{status:r.status,headers:{'content-type':r.headers.get('content-type')||'application/json;charset=utf-8','cache-control':'public,max-age=30'}})}catch{return json({ok:false,error:'live_feed_unavailable'},502)}}
async function official(u,ctx){const raw=(u.searchParams.get('date')||'').replaceAll('-','');if(!/^\d{8}$/.test(raw))return json({ok:false,error:'date_required'},400);const today=jstYmd(),target=raw===today?'https://boatraceopenapi.github.io/api/v1/today.json':`https://boatraceopenapi.github.io/api/v1/${raw.slice(0,4)}/${raw}.json`,key=new Request(`${u.origin}/api/official?date=${raw}&obpe=1`);try{const cached=await caches.default.match(key);if(cached)return cached}catch{}try{const r=await fetch(target,{headers:{accept:'application/json','user-agent':'ONE-BOAT-OBPE/1.0'}});if(!r.ok)return json({ok:false,error:`official_${r.status}`},502);const parsed=await r.json(),out=json(parsed,200,'public,max-age=60');ctx.waitUntil(Promise.resolve().then(()=>caches.default.put(key,out.clone())).catch(()=>{}));return out}catch{return json({ok:false,error:'official_unavailable'},502)}}
function settleInBackground(u,ctx){const date=u.searchParams.get('date')||jstDate();const target=`${SETTLE_API}?date=${encodeURIComponent(date)}&_auto_settle=${Date.now()}`;ctx.waitUntil(fetch(target,{headers:{accept:'application/json'},cache:'no-store'}).then(r=>r.arrayBuffer()).catch(()=>{}))}
async function runSettlement(date=jstDate()){const target=`${SETTLE_API}?date=${encodeURIComponent(date)}&_cron=${Date.now()}`;const r=await fetch(target,{headers:{accept:'application/json'},cache:'no-store'});await r.arrayBuffer();return r.ok}
async function assetResponse(request,env){if(!env?.ASSETS?.fetch)return null;const res=await env.ASSETS.fetch(request);if(!res.ok)return res;const h=new Headers(res.headers),ct=h.get('content-type')||'';if(ct.includes('text/html')){let html=await res.text();html=html.replace("function shouldFinal(r){var m=minutesLeft(r);return m!==null&&m>=0&&m<=8}","function shouldFinal(r){var m=minutesLeft(r);return m!==null&&m>=0&&m<=5}");html=html.replace("if(detailTab==='prediction')renderPredictionTab(p,p.value_score,p.selected_theory||p.current_theory||p.strategy);\nelse if(detailTab==='live')renderLiveTab(p);else renderAnalysisTab(p);","q('#detailContent').innerHTML='<div class=\"card empty\">OBPEデータを取得しています</div>';\nsetTimeout(function(){try{window.dispatchEvent(new Event('obpe:render'))}catch(e){}},0);");html=html.replaceAll('ONE BOAT V5.1','ONE BOAT OBPE');html=html.replaceAll('8分前','5分前');html=html.replace('/styles.css?v=20260915-0028','/styles.css?v=20260915-obpe10');html=html.replace('</head>','<script src="/performance-aggregates.js?v=20260915-1"></script><script src="/obpe-ui.js?v=20260915-obpe14"></script><script src="/obpe-display-fix.js?v=20260915-3"></script><script src="/obpe-tabs.js?v=20260915-3"></script><script src="/obpe-live-six-lanes.js?v=20260915-1"></script><script src="/obpe-persist.js?v=20260915-5"></script><script src="/obpe-history.js?v=20260915-3"></script><script src="/obpe-history-odds-labels.js?v=20260915-1"></script></head>');h.set('cache-control','no-store');h.set('x-one-boat-engine',MODEL_VERSION);return new Response(html,{status:res.status,headers:h})}return new Response(res.body,{status:res.status,headers:h})}
export default{
  async fetch(request,env,ctx){try{const u=new URL(request.url);if(u.pathname==='/api/health')return json({ok:true,service:'ONE BOAT',engine:'OBPE',version:'2026.09-obpe19',model_version:MODEL_VERSION,final_lock_minutes:5,recalc_minutes:10,min_race_stake_yen:3000,max_race_stake_yen:5000,max_stake_per_pick_yen:2000,point_limit:null,immutable_prediction_history:true,auto_settlement_interval_seconds:60,performance_breakdowns:true,history_result_filter:true,history_odds_labels:true,head_probability_guard:0.09,six_boat_live_view:true});if(u.pathname==='/api/config')return json({ok:true,engine:'OBPE',model_version:MODEL_VERSION,logic:'展開予測 × 確率分布 × 市場評価差 × 不確実性',min_race_stake_yen:3000,max_race_stake_yen:5000,max_stake_per_pick_yen:2000,stake_unit_yen:100,final_lock_minutes:5,recalc_minutes:10,points_rule:'no fixed limit; budget and value constrained',score_gate:'disabled',enter_definition:'締切5分前の最終購入判定。3連単上位確率と購入価値を両立し、1着確率9%以上の頭候補を保護して3,000〜5,000円を1点最大2,000円で配分できる時だけENTER',probability_rule:'120通りを正規化し経験率Shrinkage補正。不確実性を安全側に反映',portfolio_rule:'1着確率9%以上の頭候補を保護。本線・対抗を優先し、頭候補を十分にカバーできない場合は見送り。抑え・高配当は価値が残るもののみ。',odds_rule:'BoatraceCSV 5分前スナップショット優先、BOAT RACE公式オッズをフォールバック。5%安全バッファ',settlement_rule:'Cloudflare Cronで1分おきに結果取得・収支反映',live_data_rule:'6艇すべての進入・展示・スタ展ST等を表示。取得元に存在しない1周/まわり足/直線は捏造せず未取得表示'});if(u.pathname==='/api/official')return official(u,ctx);if(u.pathname==='/api/history')return historyProxy(request);if(u.pathname==='/api/live/predict')return predictProxy(request,ctx);if(u.pathname==='/api/detail')return proxy(request,'detail',TTL.detail);if(u.pathname==='/api/performance')return proxy(request,'performance',TTL.performance);if(u.pathname==='/api/patterns')return proxy(request,'patterns',TTL.patterns);if(u.pathname==='/api/schedule'){settleInBackground(u,ctx);return proxy(request,'schedule',TTL.schedule)}if(u.pathname.startsWith('/api/live/'))return liveFeed(request);const asset=await assetResponse(request,env);if(asset)return asset;return json({ok:false,error:'assets_binding_missing'},503)}catch(e){return json({ok:false,error:'worker_runtime_error',message:String(e?.message||e)},500)}},
  async scheduled(controller,env,ctx){ctx.waitUntil(runSettlement().catch(()=>false))}
};
