import {DEFAULT_POLICY,evaluateRace,aggregateBacktest,walkForward} from './engine.js';
const UPSTREAM='https://vtgswxrzklwynpvifbef.supabase.co/functions/v1';
const ROUTES={'/api/live':'one-boat-live-api','/api/detail':'boat-ai-race-detail','/api/performance':'boat-ai-performance','/api/patterns':'one-boat-venue-patterns','/api/schedule':'boat-ai-schedule'};
const TTL={'/api/live':30,'/api/detail':20,'/api/performance':120,'/api/patterns':3600,'/api/schedule':300};
function json(x,status=200){return new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store'}})}
async function upstream(request,fn,path,ctx,suffix=''){const src=new URL(request.url),target=new URL(`${UPSTREAM}/${fn}${suffix}`);target.search=src.search;const key=new Request(src.toString(),{method:'GET'});if(request.method==='GET'){const cached=await caches.default.match(key);if(cached)return cached}const headers=new Headers(request.headers);['host','cookie','origin','referer'].forEach(h=>headers.delete(h));const init={method:request.method,headers,redirect:'follow'};if(!['GET','HEAD'].includes(request.method))init.body=request.body;try{const r=await fetch(target,init);const h=new Headers(r.headers);h.delete('set-cookie');h.set('cache-control',`public,max-age=${TTL[path]||30}`);const out=new Response(r.body,{status:r.status,headers:h});if(request.method==='GET'&&r.ok)ctx.waitUntil(caches.default.put(key,out.clone()).catch(()=>{}));return out}catch{return json({ok:false,error:'upstream_unavailable'},502)}}
async function official(u,ctx){const raw=(u.searchParams.get('date')||'').replaceAll('-','');if(!/^\d{8}$/.test(raw))return json({ok:false,error:'date_required'},400);const target=`https://boatraceopenapi.github.io/api/v1/${raw.slice(0,4)}/${raw}.json`;const key=new Request(`${u.origin}/api/official?date=${raw}`);const cached=await caches.default.match(key);if(cached)return cached;try{const r=await fetch(target,{headers:{accept:'application/json'}});if(!r.ok)return json({ok:false,error:`official_${r.status}`},502);const out=new Response(r.body,{status:200,headers:{'content-type':'application/json;charset=utf-8','cache-control':'public,max-age=300'}});ctx.waitUntil(caches.default.put(key,out.clone()).catch(()=>{}));return out}catch{return json({ok:false,error:'official_unavailable'},502)}}
async function body(request){try{return await request.json()}catch{return null}}
export default{async fetch(request,env,ctx){const u=new URL(request.url);
if(u.pathname==='/api/health')return json({ok:true,service:'ONE BOAT',version:'2026.09-live2',architecture:'edge-cache-first',engine:'roi-guard+walk-forward',max_stake_yen:DEFAULT_POLICY.max_stake_yen});
if(u.pathname==='/api/config')return json({ok:true,...DEFAULT_POLICY,enter_rule:'value_score>=min && ROI guard passed && stake_total_yen>0'});
if(u.pathname==='/api/official')return official(u,ctx);
if(u.pathname==='/api/evaluate'&&request.method==='POST'){const x=await body(request);if(!x?.race)return json({ok:false,error:'race_required'},400);return json({ok:true,result:evaluateRace(x.race,x.policy||DEFAULT_POLICY,x.history||{})});}
if(u.pathname==='/api/backtest'&&request.method==='POST'){const x=await body(request);const rows=Array.isArray(x?.rows)?x.rows:[];return json({ok:true,summary:aggregateBacktest(rows),walk_forward:walkForward(rows,Number(x?.train_ratio)||.7),warning:rows.length?'':'no historical rows supplied'});}
if(u.pathname.startsWith('/api/live/'))return upstream(request,'one-boat-live-api','/api/live',ctx,u.pathname.slice('/api/live'.length));
const fn=ROUTES[u.pathname];if(fn)return upstream(request,fn,u.pathname,ctx);return env.ASSETS.fetch(request)}};