const SOURCE_ORIGIN='https://boat-kaiseki.com';
const VENUES=['桐生','戸田','江戸川','平和島','多摩川','浜名湖','蒲郡','常滑','津','三国','びわこ','住之江','尼崎','鳴門','丸亀','児島','宮島','徳山','下関','若松','芦屋','福岡','唐津','大村'];
function json(data,status=200,cache='no-store'){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':cache}})}
async function asset(request,env,path,contentType){const u=new URL(request.url);u.pathname=path;u.search='';const r=await env.ASSETS.fetch(new Request(u,request));const h=new Headers(r.headers);if(contentType)h.set('content-type',contentType);h.set('cache-control','no-store, max-age=0');h.set('x-content-type-options','nosniff');return new Response(r.body,{status:r.status,headers:h})}
function num(v){const n=Number(v||0);return Number.isFinite(n)?n:0}
function pad(v){return String(v).padStart(2,'0')}
function jstDate(){return new Date(Date.now()+32400000).toISOString().slice(0,10)}
function jstYmd(){return jstDate().replaceAll('-','')}
function hmMin(hm){const m=String(hm||'').match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function nowMin(){const d=new Date(Date.now()+32400000);return d.getUTCHours()*60+d.getUTCMinutes()}
function enter(r){const p=r?.prediction||{};return String(r?.decision||p?.decision||'').toUpperCase()==='ENTER'&&num(r?.stake_total_yen??p?.stake_total_yen)>0}
function decision(r){return String(r?.decision||r?.prediction?.decision||'').toUpperCase()}
function stake(r){return num(r?.stake_total_yen??r?.prediction?.stake_total_yen)}
async function sourceHistory(params={}){const u=new URL('/api/history',SOURCE_ORIGIN);Object.entries(params).forEach(([k,v])=>v!==undefined&&v!==null&&v!==''&&u.searchParams.set(k,String(v)));const r=await fetch(u,{headers:{accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`history_${r.status}`);const d=await r.json();return Array.isArray(d?.records)?d.records:[]}
async function official(date=jstDate()){const raw=String(date).replaceAll('-',''),target=raw===jstYmd()?'https://boatraceopenapi.github.io/api/v1/today.json':`https://boatraceopenapi.github.io/api/v1/${raw.slice(0,4)}/${raw}.json`;const r=await fetch(target,{headers:{accept:'application/json','user-agent':'ONE-BOAT-CUSTOMER/1.0'}});if(!r.ok)throw new Error(`official_${r.status}`);return r.json()}
function stadiumsOf(o){return o?.programs?.stadiums||{}}
function scheduleRaces(st){if(!st?.races)return[];return Object.entries(st.races).map(([rn,r])=>({race_no:num(r?.race_number??rn),deadline:r?.closed_at||r?.close_time||null,close_min:hmMin(r?.closed_at||r?.close_time)})).filter(x=>x.race_no>=1&&x.race_no<=12).sort((a,b)=>a.race_no-b.race_no)}
function recordState(rec,closed=false){if(!rec)return closed?'CLOSED':'PENDING';if(enter(rec))return rec.settlement?'SETTLED':'PUBLIC';const d=decision(rec);if(closed)return'CLOSED';if(d==='WATCH'||d==='FINALIZING')return'WATCH';if(d==='SKIP')return'SKIP';return'PENDING'}
function noteFor(state){return state==='WATCH'?'直前情報を確認中':state==='SKIP'?'購入条件を満たさず見送り':state==='CLOSED'?'レース終了':state==='PENDING'?'判定前':''}
function publicItem(r,scheduleMap){const code=num(r.venue_code),rn=num(r.race_no),sc=scheduleMap?.get(`${code}-${rn}`);return {...r,venue_code:code,venue_name:VENUES[code-1]||`場${code}`,race_no:rn,deadline:r.deadline||r.close_time||sc?.deadline||null}}
async function buildOverview(){const date=jstDate();const [off,rows]=await Promise.all([official(date),sourceHistory({date,limit:500})]);const stMap=stadiumsOf(off),now=nowMin(),byVenue=new Map(),scheduleMap=new Map();for(const r of rows){const c=num(r.venue_code);if(!byVenue.has(c))byVenue.set(c,[]);byVenue.get(c).push(r)}const venues=[];for(let code=1;code<=24;code++){const st=stMap[String(code)]||stMap[pad(code)],rs=scheduleRaces(st);rs.forEach(x=>scheduleMap.set(`${code}-${x.race_no}`,x));if(!rs.length){venues.push({code,name:VENUES[code-1],state:'NOEVENT',next_race_no:null,next_deadline:null,public_count:0});continue}const next=rs.find(x=>x.close_min===null||x.close_min>=now-1);const vr=(byVenue.get(code)||[]).slice().sort((a,b)=>num(a.race_no)-num(b.race_no));const publicRows=vr.filter(enter);if(!next){venues.push({code,name:VENUES[code-1],state:'FINISHED',next_race_no:12,next_deadline:rs[rs.length-1]?.deadline||null,public_count:publicRows.length});continue}const futurePublic=publicRows.find(r=>num(r.race_no)>=next.race_no&&!r.settlement),targetRec=futurePublic||vr.find(r=>num(r.race_no)===next.race_no),targetNo=targetRec?num(targetRec.race_no):next.race_no,targetSc=rs.find(x=>x.race_no===targetNo)||next,state=recordState(targetRec,false);venues.push({code,name:VENUES[code-1],state,next_race_no:targetNo,next_deadline:targetSc?.deadline||null,public_count:publicRows.length})}const publicItems=rows.filter(enter).sort((a,b)=>num(a.venue_code)-num(b.venue_code)||num(a.race_no)-num(b.race_no)).map(r=>publicItem(r,scheduleMap));return{ok:true,date,active_count:venues.filter(v=>v.state!=='NOEVENT'&&v.state!=='FINISHED').length,public_count:publicItems.length,venues,public_items:publicItems}}
async function buildVenue(code){code=num(code);if(code<1||code>24)throw new Error('bad_venue');const date=jstDate();const [off,rows]=await Promise.all([official(date),sourceHistory({date,venue:code,limit:100})]);const stMap=stadiumsOf(off),st=stMap[String(code)]||stMap[pad(code)],rs=scheduleRaces(st),now=nowMin(),recBy=new Map(rows.map(r=>[num(r.race_no),r]));if(!rs.length)return{ok:true,date,code,name:VENUES[code-1],state:'NOEVENT',public_count:0,races:[]};const races=rs.map(sc=>{const rec=recBy.get(sc.race_no)||null,closed=sc.close_min!==null&&sc.close_min<now-1,state=recordState(rec,closed);return{race_no:sc.race_no,deadline:sc.deadline,state,note:noteFor(state),record:rec}});const next=races.find(r=>{const m=hmMin(r.deadline);return m===null||m>=now-1});const publicCount=rows.filter(enter).length;let state='FINISHED';if(next)state=next.state;if(next&&state==='PENDING'){const future=races.find(r=>r.race_no>=next.race_no&&(r.state==='PUBLIC'||r.state==='WATCH'||r.state==='SKIP'));if(future)state=future.state}return{ok:true,date,code,name:VENUES[code-1],state,public_count:publicCount,races}}
function metric(rows){let races=0,hits=0,stakeY=0,payoutY=0;for(const r of rows){if(!enter(r)||!r.settlement)continue;races++;const st=stake(r),pay=num(r.settlement?.payout_yen);stakeY+=st;payoutY+=pay;if(r.settlement?.hit===true)hits++}const profit=payoutY-stakeY;return{races,hits,hit_rate:races?hits/races*100:0,stake_yen:stakeY,payout_yen:payoutY,profit_yen:profit,roi:stakeY?payoutY/stakeY*100:0}}
function isoDaysAgo(n){const d=new Date(Date.now()+32400000-n*86400000);return d.toISOString().slice(0,10)}
async function stats(){const rows=await sourceHistory({limit:2000});const today=jstDate(),d7=isoDaysAgo(6),d30=isoDaysAgo(29),dated=rows.filter(r=>r.race_date);const latest=rows.filter(r=>enter(r)&&r.settlement).sort((a,b)=>String(b.race_date).localeCompare(String(a.race_date))||num(b.race_no)-num(a.race_no)).slice(0,12).map(r=>({race_date:r.race_date,venue_name:VENUES[num(r.venue_code)-1]||`場${r.venue_code}`,race_no:num(r.race_no),hit:r.settlement?.hit===true,trifecta:r.settlement?.result?.trifecta||r.settlement?.trifecta||'',stake_yen:stake(r),payout_yen:num(r.settlement?.payout_yen),profit_yen:Number.isFinite(Number(r.settlement?.profit_yen))?Number(r.settlement.profit_yen):num(r.settlement?.payout_yen)-stake(r)}));return{ok:true,scope:'public_only',today:metric(dated.filter(r=>r.race_date===today)),days7:metric(dated.filter(r=>r.race_date>=d7&&r.race_date<=today)),days30:metric(dated.filter(r=>r.race_date>=d30&&r.race_date<=today)),all:metric(rows),latest}}
export default{async fetch(request,env){const u=new URL(request.url);try{if(u.pathname==='/api/health')return json({ok:true,service:'ONE BOAT CUSTOMER',version:'2026-09-17.24v1',source:'management-history+official-schedule',customer_view_only:true});if(u.pathname==='/api/public/overview')return json(await buildOverview());if(u.pathname==='/api/public/venue')return json(await buildVenue(u.searchParams.get('code')));if(u.pathname==='/api/public/today'){const o=await buildOverview();return json({ok:true,date:o.date,count:o.public_count,public_count:o.public_count,items:o.public_items})}if(u.pathname==='/api/public/stats')return json(await stats());if(u.pathname==='/hero-top.jpg')return asset(request,env,'/hero-top.webp','image/jpeg');if(u.pathname==='/'||u.pathname==='/index.html')return asset(request,env,'/index.html','text/html;charset=utf-8');return asset(request,env,u.pathname)}catch(e){return json({ok:false,error:'temporarily_unavailable',message:String(e?.message||e)},502)}}};
