const SITE_API='https://imhzjlxbnovjvqlyawmg.supabase.co/functions/v1/one-boat-site-api';
const LIVE_FEED='https://imhzjlxbnovjvqlyawmg.supabase.co/functions/v1/one-boat-live-feed';
const MODEL_VERSION='OBPE-1.0.2';
const TTL={predict:0,detail:20,performance:30,patterns:120,schedule:30};
function json(x,status=200,cache='no-store'){return new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':cache}})}
function jstYmd(){return new Date(Date.now()+9*3600*1000).toISOString().slice(0,10).replaceAll('-','')}
async function proxy(request,suffix,ttl=20){const src=new URL(request.url),target=new URL(`${SITE_API}/${suffix}`);target.search=src.search;const headers=new Headers(request.headers);['host','cookie','origin','referer'].forEach(h=>headers.delete(h));const init={method:request.method,headers,redirect:'follow'};if(!['GET','HEAD'].includes(request.method))init.body=request.body;try{const r=await fetch(target,init),h=new Headers(r.headers);h.delete('set-cookie');h.set('cache-control',ttl>0&&request.method==='GET'?`public,max-age=${ttl}`:'no-store');return new Response(r.body,{status:r.status,headers:h})}catch{return json({ok:false,error:'site_api_unavailable'},502)}}
async function liveFeed(request){const src=new URL(request.url),path=src.pathname.slice('/api/live/'.length),target=new URL(LIVE_FEED);target.searchParams.set('path',path);for(const[k,v]of src.searchParams)target.searchParams.set(k,v);try{const r=await fetch(target,{headers:{accept:'application/json'}});return new Response(r.body,{status:r.status,headers:{'content-type':r.headers.get('content-type')||'application/json;charset=utf-8','cache-control':'public,max-age=30'}})}catch{return json({ok:false,error:'live_feed_unavailable'},502)}}
async function official(u,ctx){const raw=(u.searchParams.get('date')||'').replaceAll('-','');if(!/^\d{8}$/.test(raw))return json({ok:false,error:'date_required'},400);const today=jstYmd(),target=raw===today?'https://boatraceopenapi.github.io/api/v1/today.json':`https://boatraceopenapi.github.io/api/v1/${raw.slice(0,4)}/${raw}.json`,key=new Request(`${u.origin}/api/official?date=${raw}&obpe=1`);try{const cached=await caches.default.match(key);if(cached)return cached}catch{}try{const r=await fetch(target,{headers:{accept:'application/json','user-agent':'ONE-BOAT-OBPE/1.0'}});if(!r.ok)return json({ok:false,error:`official_${r.status}`},502);const parsed=await r.json(),out=json(parsed,200,'public,max-age=60');ctx.waitUntil(Promise.resolve().then(()=>caches.default.put(key,out.clone())).catch(()=>{}));return out}catch{return json({ok:false,error:'official_unavailable'},502)}}
async function assetResponse(request,env){if(!env?.ASSETS?.fetch)return null;const res=await env.ASSETS.fetch(request);if(!res.ok)return res;const h=new Headers(res.headers),ct=h.get('content-type')||'';if(ct.includes('text/html')){let html=await res.text();html=html.replace("function shouldFinal(r){var m=minutesLeft(r);return m!==null&&m>=0&&m<=8}","function shouldFinal(r){var m=minutesLeft(r);return m!==null&&m>=0&&m<=5}");html=html.replaceAll('ONE BOAT V5.1','ONE BOAT OBPE');html=html.replaceAll('8分前','5分前');html=html.replace('</head>','<script src="/obpe-ui.js?v=20260915-obpe6"></script><script src="/obpe-display-fix.js?v=20260915-1"></script><script src="/obpe-tabs.js?v=20260915-1"></script><script src="/obpe-persist.js?v=20260915-1"></script></head>');h.set('cache-control','no-store');h.set('x-one-boat-engine',MODEL_VERSION);return new Response(html,{status:res.status,headers:h})}return new Response(res.body,{status:res.status,headers:h})}
export default{async fetch(request,env,ctx){try{const u=new URL(request.url);if(u.pathname==='/api/health')return json({ok:true,service:'ONE BOAT',engine:'OBPE',version:'2026.09-obpe6',model_version:MODEL_VERSION,final_lock_minutes:5,recalc_minutes:10,max_race_stake_yen:5000});if(u.pathname==='/api/config')return json({ok:true,engine:'OBPE',model_version:MODEL_VERSION,logic:'展開予測 × 確率分布 × 市場評価差 × 不確実性',max_race_stake_yen:5000,stake_unit_yen:100,final_lock_minutes:5,recalc_minutes:10,points_rule:'dynamic',score_gate:'disabled',probability_rule:'120通りを正規化し経験率Shrinkage補正。不確実性を安全側に反映',odds_rule:'BoatraceCSV 5分前スナップショット優先、BOAT RACE公式オッズをフォールバック。5%安全バッファ'});if(u.pathname==='/api/official')return official(u,ctx);if(u.pathname==='/api/live/predict')return proxy(request,'predict',TTL.predict);if(u.pathname==='/api/detail')return proxy(request,'detail',TTL.detail);if(u.pathname==='/api/performance')return proxy(request,'performance',TTL.performance);if(u.pathname==='/api/patterns')return proxy(request,'patterns',TTL.patterns);if(u.pathname==='/api/schedule')return proxy(request,'schedule',TTL.schedule);if(u.pathname.startsWith('/api/live/'))return liveFeed(request);const asset=await assetResponse(request,env);if(asset)return asset;return json({ok:false,error:'assets_binding_missing'},503)}catch(e){return json({ok:false,error:'worker_runtime_error',message:String(e?.message||e)},500)}}};
