import {DEFAULT_POLICY,evaluateRace,aggregateBacktest,walkForward} from './engine.js';
const UPSTREAM='https://vtgswxrzklwynpvifbef.supabase.co/functions/v1';
const ROUTES={'/api/live':'one-boat-live-api','/api/detail':'boat-ai-race-detail','/api/performance':'boat-ai-performance','/api/patterns':'one-boat-venue-patterns','/api/schedule':'boat-ai-schedule'};
const TTL={'/api/live':30,'/api/detail':20,'/api/performance':120,'/api/patterns':3600,'/api/schedule':300};
function json(x,status=200,cache='no-store'){return new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':cache}})}
async function upstream(request,fn,path,ctx,suffix=''){const src=new URL(request.url),target=new URL(`${UPSTREAM}/${fn}${suffix}`);target.search=src.search;const key=new Request(src.toString(),{method:'GET'});try{if(request.method==='GET'){const cached=await caches.default.match(key);if(cached)return cached}}catch{}const headers=new Headers(request.headers);['host','cookie','origin','referer'].forEach(h=>headers.delete(h));const init={method:request.method,headers,redirect:'follow'};if(!['GET','HEAD'].includes(request.method))init.body=request.body;try{const r=await fetch(target,init),h=new Headers(r.headers);h.delete('set-cookie');h.set('cache-control',`public,max-age=${TTL[path]||30}`);const out=new Response(r.body,{status:r.status,headers:h});if(request.method==='GET'&&r.ok)ctx.waitUntil(Promise.resolve().then(()=>caches.default.put(key,out.clone())).catch(()=>{}));return out}catch{return json({ok:false,error:'upstream_unavailable'},502)}}
function jstYmd(){const d=new Date(Date.now()+9*3600*1000);return d.toISOString().slice(0,10).replaceAll('-','')}
async function official(u,ctx){const raw=(u.searchParams.get('date')||'').replaceAll('-','');if(!/^\d{8}$/.test(raw))return json({ok:false,error:'date_required'},400);const today=jstYmd(),target=raw===today?'https://boatraceopenapi.github.io/api/v1/today.json':`https://boatraceopenapi.github.io/api/v1/${raw.slice(0,4)}/${raw}.json`,key=new Request(`${u.origin}/api/official?date=${raw}&v=4`);try{const cached=await caches.default.match(key);if(cached)return cached}catch{}try{const r=await fetch(target,{headers:{accept:'application/json','user-agent':'ONE-BOAT/1.0'}});if(!r.ok)return json({ok:false,error:`official_${r.status}`},502);const parsed=await r.json(),out=json(parsed,200,'public,max-age=60');ctx.waitUntil(Promise.resolve().then(()=>caches.default.put(key,out.clone())).catch(()=>{}));return out}catch{return json({ok:false,error:'official_unavailable'},502)}}
async function body(request){try{return await request.json()}catch{return null}}
export default{async fetch(request,env,ctx){try{const u=new URL(request.url);if(u.pathname==='/api/health')return json({ok:true,service:'ONE BOAT',version:'2026.09-live4',architecture:'edge-cache-first',engine:'roi-guard+walk-forward',max_stake_yen:DEFAULT_POLICY.max_stake_yen,final_lock_minutes:8});if(u.pathname==='/api/config')return json({ok:true,...DEFAULT_POLICY,final_lock_minutes:8,enter_rule:'value_score>=min && ROI guard passed && stake_total_yen>0'});if(u.pathname==='/api/official')return official(u,ctx);if(u.pathname==='/api/evaluate'&&request.method==='POST'){const x=await body(request);if(!x?.race)return json({ok:false,error:'race_required'},400);return json({ok:true,result:evaluateRace(x.race,x.policy||DEFAULT_POLICY,x.history||{})})}if(u.pathname==='/api/backtest'&&request.method==='POST'){const x=await body(request),rows=Array.isArray(x?.rows)?x.rows:[];return json({ok:true,summary:aggregateBacktest(rows),walk_forward:walkForward(rows,Number(x?.train_ratio)||.7),warning:rows.length?'':'no historical rows supplied'})}if(u.pathname.startsWith('/api/live/'))return upstream(request,'one-boat-live-api','/api/live',ctx,u.pathname.slice('/api/live'.length));const fn=ROUTES[u.pathname];if(fn)return upstream(request,fn,u.pathname,ctx);if(env?.ASSETS?.fetch)return env.ASSETS.fetch(request);return json({ok:false,error:'assets_binding_missing'},503)}catch(e){return json({ok:false,error:'worker_runtime_error',message:String(e?.message||e)},500)}}};