import fs from 'node:fs';
const html=fs.readFileSync('public/index.html','utf8');
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
if(!scripts.length) throw new Error('inline script missing');
for(const script of scripts) new Function(script);
const venues=['桐生','戸田','江戸川','平和島','多摩川','浜名湖','蒲郡','常滑','津','三国','びわこ','住之江','尼崎','鳴門','丸亀','児島','宮島','徳山','下関','若松','芦屋','福岡','唐津','大村'];
for(const v of venues) if(!html.includes("'"+v+"'")) throw new Error('missing venue '+v);
for(const id of ['screen-home','screen-venues','screen-races','screen-detail','screen-result','screen-performance']) if(!html.includes('id="'+id+'"')) throw new Error('missing screen '+id);
if(!html.includes("m<=8")) throw new Error('8-minute finalization rule missing');
if(!html.includes("d==='ENTER'&&stake!==null&&stake>0")) throw new Error('ENTER positive-stake rule missing');
if(!html.includes("r.phase==='future'")) throw new Error('future-race pending rule missing');
if(!html.includes('未判定')) throw new Error('future-race label missing');
console.log('ui-smoke ok: inline JS parses, 24 venues and production display rules present');
