const $=s=>document.querySelector(s);
const API='https://imhzjlxbnovjvqlyawmg.supabase.co/functions/v1/one-boat-race-analysis-api';
const VENUES=['桐生','戸田','江戸川','平和島','多摩川','浜名湖','蒲郡','常滑','津','三国','びわこ','住之江','尼崎','鳴門','丸亀','児島','宮島','徳山','下関','若松','芦屋','福岡','唐津','大村'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const params=new URLSearchParams(location.search);
const CODE=Number(params.get('venue')||params.get('code'));
const RACE=Number(params.get('race'));
const jstDate=()=>new Date(Date.now()+32400000).toISOString().slice(0,10);
const DATE=/^\d{4}-\d{2}-\d{2}$/.test(params.get('date')||'')?params.get('date'):jstDate();
let DATA=null;
let MY={first:null,second:null,third:null};

function missing(v){return v===null||v===undefined||v===''}
function value(v,suffix=''){return missing(v)?'—':`${v}${suffix}`}
function fixed(v,d=2,suffix=''){if(missing(v)||!Number.isFinite(Number(v)))return'—';return `${Number(v).toFixed(d)}${suffix}`}
function pct(v){return missing(v)||!Number.isFinite(Number(v))?'—':`${Number(v).toFixed(1)}%`}
function hm(v){const m=String(v||'').match(/(\d{1,2}:\d{2})/);return m?m[1]:'—'}
function dateJp(v){if(!v)return'—';const m=String(v).match(/(\d{4})-(\d{2})-(\d{2})/);return m?`${Number(m[2])}/${Number(m[3])}`:String(v)}
function updated(v){if(!v)return'—';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'Asia/Tokyo'}).format(d)}
function laneBadge(n){return `<span class="lane-box lane-${n}">${n}</span>`}
function stText(v){if(missing(v)||!Number.isFinite(Number(v)))return'—';const n=Number(v);return n<0?`F${Math.abs(n).toFixed(2)}`:n.toFixed(2)}
function venueName(){return VENUES[CODE-1]||`場${CODE}`}
function exMap(d){return new Map((d?.exhibition_detail?.boats||[]).map(x=>[Number(x.lane),x]))}

function renderRacers(d){const xs=d?.racers||[],em=exMap(d);$('#racer-list').innerHTML=xs.map(r=>{const o=r.overall||{},course=em.get(Number(r.lane))?.course??null,c=course===null?null:r.by_course?.[String(course)]||null;return `<article class="racer-card">
  <div class="racer-main">${laneBadge(r.lane)}<div class="racer-name"><strong>${esc(r.name||'選手情報待ち')}</strong><small>${r.racer_id?`${esc(r.racer_id)}番`:'登録番号 —'} ・ ${course===null?'進入 —':`${course}コース`}</small></div><span class="racer-grade">${course===null?'—':`${course}C`}</span></div>
  <div class="racer-stats"><div><span>全体勝率</span><b>${pct(o.win_rate)}</b></div><div><span>2連対率</span><b>${pct(o.top2_rate)}</b></div><div><span>3連対率</span><b>${pct(o.top3_rate)}</b></div><div><span>平均ST</span><b>${fixed(o.avg_st,3)}</b></div></div>
  <div class="equipment-row"><div><span>全体サンプル</span><strong>${missing(o.sample_count)?'—':`${o.sample_count}走`}</strong></div><div><span>コース別平均ST</span><strong>${fixed(c?.avg_st,3)}</strong></div><div><span>コース別サンプル</span><strong>${missing(c?.sample_count)?'—':`${c.sample_count}走`}</strong></div><div><span>STばらつき</span><strong>${fixed(c?.st_sd,3)}</strong></div></div>
</article>`}).join('')||'<div class="empty-card"><strong>選手情報はデータ未連携です</strong><p>正式APIに値が入るまで推測値は表示しません。</p></div>'}

function originalText(original,lane){if(original?.available===false)return original?.reason==='not_provided_at_edogawa'?'非提供':'—';const boat=(original?.boats||[]).find(x=>Number(x.lane)===Number(lane));if(!boat?.values?.length)return'—';const xs=boat.values.filter(x=>!missing(x?.value));return xs.length?xs.map(x=>`${esc(x.label||'計測')} ${value(x.value)}`).join(' / '):'—'}
function renderExhibition(d){const ex=d?.exhibition_detail||{},original=d?.original_exhibition||null,xs=ex.boats||[];$('#exhibition-list').innerHTML=`<div class="ex-head"><span>艇</span><span>進入</span><span>展示ST</span><span>展示タイム</span></div>${xs.map(r=>`<div class="ex-row">${laneBadge(r.lane)}<span>${value(r.course)}</span><span>${stText(r.start_timing)}</span><span>${fixed(r.exhibition_time,2)}</span><div class="ex-sub"><div class="wide"><span>オリジナル展示</span><b>${originalText(original,r.lane)}</b></div><div><span>一周</span><b>${fixed(r.lap_time,2)}</b></div><div><span>半周</span><b>${fixed(r.half_lap_time,2)}</b></div><div><span>まわり足</span><b>${fixed(r.turning,2)}</b></div><div><span>直線</span><b>${fixed(r.straight,2)}</b></div><div><span>チルト</span><b>${fixed(r.tilt,1)}</b></div></div></div>`).join('')}`;
  const notes=[];if(CODE===3||original?.reason==='not_provided_at_edogawa')notes.push('江戸川はオリジナル展示の提供対象外です。');if(!xs.length)notes.push('展示データは現在未生成です。');if(ex.updated_at)notes.push(`展示更新 ${updated(ex.updated_at)}`);$('#exhibition-note').textContent=notes.join(' ');const live=xs.some(r=>!missing(r.exhibition_time)||!missing(r.start_timing)||!missing(r.course)||!missing(r.lap_time)||!missing(r.half_lap_time)||!missing(r.turning)||!missing(r.straight));$('#exhibition-status').textContent=live?'正式データ取得済み':'直前データ待ち'}

function renderSurface(d){const t=d?.tide||{};const cards=[['天気','—'],['気温','—'],['水温','—'],['風向','—'],['風速','—'],['波高','—'],['潮位',value(t.tide_level)],['潮状態',value(t.current_state)],['満潮',value(t.high_tide)],['干潮',value(t.low_tide)]];$('#surface-grid').innerHTML=cards.map(([label,val])=>`<div class="surface-card"><span>${label}</span><strong>${esc(val)}</strong></div>`).join('');const sui=d?.source_status?.sui;$('#tide-note').textContent=`気象・水面数値は専用APIの正式応答に含まれる項目だけを表示します。現在は${sui==='available'?'取得元あり・表示値未連携':'データ未連携'}です。潮位・干満は正式ソース未接続のため推測表示しません。`}

function evalValue(v){if(missing(v))return'—';if(typeof v==='number')return Number.isInteger(v)?String(v):Number(v).toFixed(2);return esc(v)}
function renderEngine(e){const items=[['展示評価',e?.exhibition],['ST評価',e?.st],['モーター評価',e?.motor],['コース評価',e?.course],['総合評価',e?.total]];$('#engine-summary').innerHTML=items.map(([label,v])=>`<div class="engine-metric"><span>${label}</span><strong>${evalValue(v)}</strong></div>`).join('');const has=items.some(([,v])=>!missing(v));$('#engine-rankings').innerHTML=has?`<div class="data-note">予想エンジンの正式 score_breakdown に存在する値のみ表示しています。${e?.updated_at?` 更新 ${updated(e.updated_at)}`:''}</div>`:'<div class="empty-card"><strong>正式評価データ待ち</strong><p>現在の score_breakdown は空のため、展示・ST・モーター・コース・総合評価はすべて「—」が正式表示です。④側では再計算しません。</p></div>'}

function renderOdds(o){const items=Array.isArray(o?.items)?o.items:[];$('#odds-updated').textContent=`更新 ${updated(o?.updated_at)}${items.length?` ・ ${items.length}通り`:''}`;if(!items.length){$('#odds-content').className='empty-card';$('#odds-content').innerHTML='<strong>3連単オッズはデータ未生成です</strong><p>正式APIが返した値だけを表示します。過去オッズや推測倍率では補完しません。</p>';return}const sorted=items.slice().sort((a,b)=>String(a.combination||'').localeCompare(String(b.combination||''),'ja',{numeric:true}));$('#odds-content').className='odds-grid';$('#odds-content').innerHTML=sorted.map(x=>`<div class="odds-item"><b>${esc(x.combination||'—')}</b><span>${fixed(x.odds,1,'倍')}</span></div>`).join('')}

function myKey(){return DATA?`oneboat_my_${DATA.race.date}_${DATA.race.venue_code}_${DATA.race.race_no}`:''}
function loadMy(){try{const x=JSON.parse(localStorage.getItem(myKey())||'{}');MY={first:Number(x.first)||null,second:Number(x.second)||null,third:Number(x.third)||null}}catch{MY={first:null,second:null,third:null}}}
function saveMy(){try{localStorage.setItem(myKey(),JSON.stringify(MY))}catch{}renderMy()}
function renderMy(){document.querySelectorAll('.lane-buttons').forEach(box=>{const place=box.dataset.place;box.innerHTML=[1,2,3,4,5,6].map(n=>{const selected=MY[place]===n,used=Object.entries(MY).some(([k,v])=>k!==place&&v===n);return `<button class="lane-choice${selected?' selected':''}" type="button" data-place="${place}" data-lane="${n}" ${used?'disabled':''}>${n}</button>`}).join('')});document.querySelectorAll('.lane-choice').forEach(b=>b.addEventListener('click',()=>{MY[b.dataset.place]=Number(b.dataset.lane);saveMy()}));$('#my-ticket').textContent=`${MY.first||'—'} - ${MY.second||'—'} - ${MY.third||'—'}`}

function setupTabs(){document.querySelectorAll('.analysis-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.analysis-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector(`[data-panel="${b.dataset.tab}"]`)?.classList.add('active')}))}
function render(d){DATA=d;const race=d.race||{};$('#race-title').textContent=`${venueName()} ${race.race_no||RACE}R`;$('#race-subtitle').textContent='専用APIから取得した正式データだけを表示';$('#race-date').textContent=dateJp(race.date||DATE);$('#race-deadline').textContent='—';$('#race-updated').textContent=updated(d.trifecta_odds?.updated_at||d.exhibition_detail?.updated_at||d.original_exhibition?.updated_at);const st=$('#race-state');st.textContent='分析データ';st.className='state-badge live';$('#official-link').href=`/today.html?venue=${String(CODE).padStart(2,'0')}&race=${RACE}`;renderRacers(d);renderExhibition(d);renderSurface(d);renderEngine(d.official_evaluation);renderOdds(d.trifecta_odds);loadMy();renderMy();document.body.setAttribute('aria-busy','false')}
async function load(){if(!(CODE>=1&&CODE<=24&&RACE>=1&&RACE<=12)){const m=$('#page-message');m.hidden=false;m.textContent='場またはレース番号が正しくありません。本日の予想からレースを選び直してください。';return}document.body.setAttribute('aria-busy','true');const normalized=`/analysis.html?date=${encodeURIComponent(DATE)}&venue=${CODE}&race=${RACE}`;if(location.pathname+location.search!==normalized)history.replaceState(null,'',normalized);try{const u=new URL(API);u.searchParams.set('date',DATE);u.searchParams.set('venue',String(CODE));u.searchParams.set('race',String(RACE));const r=await fetch(u,{cache:'no-store',headers:{accept:'application/json'}});let d=null;try{d=await r.json()}catch{}if(!r.ok||!d?.ok)throw Error(d?.error||`api_${r.status}`);render(d)}catch(e){document.body.setAttribute('aria-busy','false');const m=$('#page-message');m.hidden=false;m.textContent='レース分析APIから正式データを取得できませんでした。公式予想画面には影響ありません。少し時間をおいて再読み込みしてください。';$('#race-title').textContent=`${venueName()} ${RACE}R`;$('#race-subtitle').textContent='分析データ取得待ち';$('#race-date').textContent=dateJp(DATE);$('#race-deadline').textContent='—';$('#race-updated').textContent='—';const st=$('#race-state');st.textContent='取得待ち';st.className='state-badge pending';$('#official-link').href=`/today.html?venue=${String(CODE).padStart(2,'0')}&race=${RACE}`}}

setupTabs();$('#clear-my').addEventListener('click',()=>{MY={first:null,second:null,third:null};try{localStorage.removeItem(myKey())}catch{}renderMy()});load();