const ONE_BOAT_CANONICAL_ORIGIN='https://one-boat-club.jp';
function enforceOneBoatCanonical(){
  if(location.hostname==='one-boat-customer.uk-1407-uk.workers.dev'||location.hostname==='www.one-boat-club.jp'){
    location.replace(`${ONE_BOAT_CANONICAL_ORIGIN}${location.pathname}${location.search}${location.hash}`);
    return true;
  }
  return false;
}
if(enforceOneBoatCanonical()) throw new Error('canonical_redirect');
window.addEventListener('pageshow',()=>{enforceOneBoatCanonical()});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)enforceOneBoatCanonical()});
const q=s=>document.querySelector(s);
const fmtDate=v=>{if(!v)return'—';const d=new Date(v);if(Number.isNaN(d.getTime()))return'—';return new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tokyo'}).format(d)};
const planName=p=>({guest:'未ログイン',unknown:'確認中',free:'無料会員',day_pass:'1日PASS',club_monthly:'ONE BOAT CLUB',staff:'運営アカウント'})[p]||p||'確認中';
const statusName=s=>({active:'有効',cancel_at_period_end:'解約予約済み',cancel_scheduled:'解約予約済み',expired:'期限切れ',payment_failed:'決済エラー',inactive:'無効',unavailable:'状態確認中',staff:'運営アクセス'})[s]||s||'状態確認中';
function showMessage(el,text,type='error'){if(!el)return;el.textContent=text;el.className=`message show ${type}`}
async function api(path,options={}){const r=await fetch(path,{credentials:'same-origin',cache:'no-store',headers:{'content-type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));return{r,d}}
async function getSession(){const r=await fetch('/api/member/session',{credentials:'same-origin',cache:'no-store'});return r.json().catch(()=>({ok:false,logged_in:false}))}
function safeNext(){const p=new URLSearchParams(location.search).get('next');return p&&p.startsWith('/')&&!p.startsWith('//')?p:'/mypage.html'}

async function setupSignup(){const f=q('#signup-form'),msg=q('#form-message');if(!f)return;const s=await getSession();if(s.logged_in){location.replace('/mypage.html');return}f.addEventListener('submit',async e=>{e.preventDefault();const btn=q('#submit-btn');btn.disabled=true;const body={email:q('#email').value.trim(),password:q('#password').value,age20:q('#age20').checked,terms:q('#terms').checked,privacy:q('#privacy').checked};const{r,d}=await api('/api/auth/signup',{method:'POST',body:JSON.stringify(body)});btn.disabled=false;if(!r.ok){showMessage(msg,d.message||'登録できませんでした。');return}if(d.confirmation_required){showMessage(msg,d.message||'確認メールを送信しました。','ok');f.reset();return}location.href='/mypage.html'})}
async function setupLogin(){const f=q('#login-form'),msg=q('#form-message');if(!f)return;const s=await getSession();if(s.logged_in){location.replace(safeNext());return}f.addEventListener('submit',async e=>{e.preventDefault();const btn=q('#submit-btn');btn.disabled=true;const{r,d}=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:q('#email').value.trim(),password:q('#password').value})});btn.disabled=false;if(!r.ok){showMessage(msg,d.message||'ログインできませんでした。');return}location.href=safeNext()})}
async function startCheckout(plan,button,msg){button.disabled=true;const{r,d}=await api('/api/member/checkout-intent',{method:'POST',body:JSON.stringify({plan})});button.disabled=false;if(r.status===401){location.href=`/login?next=${encodeURIComponent('/club.html?buy='+plan)}`;return}if(!r.ok){showMessage(msg,d.message||'購入準備に失敗しました。');return}if(d.url)location.href=d.url}
async function setupPlanButtons(){const buttons=[...document.querySelectorAll('[data-buy-plan]')];if(!buttons.length)return;const msg=q('#plan-message');const s=await getSession();if(s.logged_in){document.querySelectorAll('[data-member-link]').forEach(a=>{a.textContent='マイページ';a.href='/mypage.html'})}if(s.plan==='staff'){buttons.forEach(b=>{b.disabled=true;b.style.display='none'});showMessage(msg,'運営アカウントのため購入は不要です。','ok');return}for(const b of buttons)b.addEventListener('click',()=>startCheckout(b.dataset.buyPlan,b,msg));const requested=new URLSearchParams(location.search).get('buy');if(requested&&['day_pass','club_monthly'].includes(requested)&&s.logged_in){const b=document.querySelector(`[data-buy-plan="${requested}"]`);if(b)startCheckout(requested,b,msg)}}
async function openCancelPortal(button,msg){if(!confirm('月額ONE BOAT CLUBの解約手続きへ進みます。Stripeの安全な管理画面で次回更新を停止できます。'))return;button.disabled=true;const{r,d}=await api('/api/member/billing-portal',{method:'POST',body:'{}'});button.disabled=false;if(!r.ok){showMessage(msg,d.message||'解約画面を開けませんでした。');return}if(d.url)location.href=d.url}
async function setupMypage(){if(!q('#mypage'))return;const s=await getSession();if(!s.logged_in){location.replace('/login?next=%2Fmypage.html');return}q('#account-email').textContent=s.email||'—';q('#plan-name').textContent=planName(s.plan);q('#member-status').textContent=statusName(s.status);q('#status-text').textContent=s.cancel_at_period_end?'期間終了時に解約予定':statusName(s.status);q('#expiry-label').textContent=s.plan==='staff'?'運営アクセス':s.plan==='club_monthly'?'次回更新 / 利用期限':'有効期限';q('#expiry-value').textContent=s.plan==='staff'?'無期限':fmtDate(s.next_billing_at||s.access_expires_at);const msg=q('#mypage-message');if(s.status==='unavailable')showMessage(msg,'会員状態を一時的に確認できません。有料機能は安全のため解放していません。');const paid=q('#paid-entry');if(paid)paid.style.display=s.paid_access?'flex':'none';const cancel=q('#cancel-subscription');if(cancel){cancel.style.display=s.plan==='club_monthly'&&s.status==='active'&&!s.cancel_at_period_end?'flex':'none';cancel.addEventListener('click',()=>openCancelPortal(cancel,msg))}q('#logout').addEventListener('click',async()=>{await api('/api/auth/logout',{method:'POST',body:'{}'});location.href='/login'})}
async function setupPremium(){if(!q('#premium-page'))return;const s=await getSession();if(!s.logged_in||!s.paid_access)return;q('#premium-plan').textContent=planName(s.plan);q('#premium-expiry').textContent=s.plan==='staff'?'運営アクセス':fmtDate(s.next_billing_at||s.access_expires_at)}

document.addEventListener('DOMContentLoaded',()=>{setupSignup();setupLogin();setupPlanButtons();setupMypage();setupPremium()});
