import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT=process.argv[2]||'shards';
async function walk(dir){const out=[];for(const e of await fs.readdir(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())out.push(...await walk(p));else if(e.isFile()&&e.name==='backtest-v60-2y.json')out.push(p)}return out}
const files=await walk(ROOT);if(!files.length)throw new Error('no shard reports found');
const reports=[];for(const f of files)reports.push(JSON.parse(await fs.readFile(f,'utf8')));
const numeric=['total_races','pre_odds_candidates','odds_covered_candidates','odds_missing_skips','enter_races','hits','stake','returns','data_missing_skips','score_below_64','candidate_64_69','theory_mismatch','allocation_fail'];
const summary={model:'ONE BOAT V6.0-simple-six-theory',mode:'historical-safe-replay-v2-parallel',start:'2024-09-15',end:'2026-09-14',shards:reports.length};for(const k of numeric)summary[k]=reports.reduce((s,r)=>s+Number(r.summary?.[k]||0),0);
summary.profit=summary.returns-summary.stake;summary.roi=summary.stake?+(summary.returns/summary.stake*100).toFixed(1):null;summary.hit_rate=summary.enter_races?+(summary.hits/summary.enter_races*100).toFixed(1):null;summary.participation_rate=summary.total_races?+(summary.enter_races/summary.total_races*100).toFixed(1):null;summary.odds_coverage_pct=summary.pre_odds_candidates?+(summary.odds_covered_candidates/summary.pre_odds_candidates*100).toFixed(1):null;
function mergeBuckets(key){const m={};for(const r of reports)for(const [k,v] of Object.entries(r[key]||{})){const z=m[k]||(m[k]={races:0,hits:0,stake:0,returns:0});z.races+=Number(v.races||0);z.hits+=Number(v.hits||0);z.stake+=Number(v.stake||0);z.returns+=Number(v.returns||0)}for(const z of Object.values(m)){z.profit=z.returns-z.stake;z.roi=z.stake?+(z.returns/z.stake*100).toFixed(1):null;z.hit_rate=z.races?+(z.hits/z.races*100).toFixed(1):null}return m}
const misses={};for(const r of reports)for(const [k,v] of Object.entries(r.miss_types||{}))misses[k]=(misses[k]||0)+Number(v||0);
const result={summary,by_venue:mergeBuckets('by_venue'),by_theory:mergeBuckets('by_theory'),by_category:mergeBuckets('by_category'),by_score:mergeBuckets('by_score'),by_points:mergeBuckets('by_points'),by_odds_source:mergeBuckets('by_odds_source'),miss_types:misses,limitations:[...new Set(reports.flatMap(r=>r.limitations||[]))]};
await fs.mkdir('reports',{recursive:true});await fs.writeFile('reports/backtest-v60-2y.json',JSON.stringify(result,null,2));
const fmt=n=>Number(n||0).toLocaleString('ja-JP');const table=obj=>Object.entries(obj).sort((a,b)=>(b[1].roi??-1)-(a[1].roi??-1)).map(([k,v])=>`| ${k} | ${v.races} | ${v.hits} | ${v.hit_rate??'--'}% | ¥${fmt(v.stake)} | ¥${fmt(v.returns)} | ¥${fmt(v.profit)} | ${v.roi??'--'}% |`).join('\n');
const md=`# ONE BOAT V6.0 2年間バックテスト（統合）\n\n- 対象期間: ${summary.start} 〜 ${summary.end}\n- モデル: ${summary.model}\n- 再現方式: ${summary.mode}\n- 分割数: ${summary.shards}\n- 総実施レース: **${fmt(summary.total_races)}R**\n- オッズ取得前候補: **${fmt(summary.pre_odds_candidates)}R**\n- オッズ取得率: **${summary.odds_coverage_pct??'--'}%**\n- ENTER: **${fmt(summary.enter_races)}R**\n- 参加率: **${summary.participation_rate??'--'}%**\n- 的中: **${fmt(summary.hits)}R**\n- 的中率: **${summary.hit_rate??'--'}%**\n- 投資: **¥${fmt(summary.stake)}**\n- 払戻: **¥${fmt(summary.returns)}**\n- 収支: **¥${fmt(summary.profit)}**\n- 回収率: **${summary.roi??'--'}%**\n- 情報欠損見送り: ${fmt(summary.data_missing_skips)}R\n- 64未満: ${fmt(summary.score_below_64)}R\n- 64〜69候補: ${fmt(summary.candidate_64_69)}R\n- 理論/オッズ帯不一致: ${fmt(summary.theory_mismatch)}R\n- オッズ取得不能: ${fmt(summary.odds_missing_skips)}R\n- 配分不成立: ${fmt(summary.allocation_fail)}R\n\n## 理論別\n| 理論 | R | 的中 | 的中率 | 投資 | 払戻 | 収支 | ROI |\n|---|---:|---:|---:|---:|---:|---:|---:|\n${table(result.by_theory)}\n\n## 分類別\n| 分類 | R | 的中 | 的中率 | 投資 | 払戻 | 収支 | ROI |\n|---|---:|---:|---:|---:|---:|---:|---:|\n${table(result.by_category)}\n\n## 評価点別\n| 評価点 | R | 的中 | 的中率 | 投資 | 払戻 | 収支 | ROI |\n|---|---:|---:|---:|---:|---:|---:|---:|\n${table(result.by_score)}\n\n## 点数別\n| 点数 | R | 的中 | 的中率 | 投資 | 払戻 | 収支 | ROI |\n|---|---:|---:|---:|---:|---:|---:|---:|\n${table(result.by_points)}\n\n## オッズソース別\n| ソース | R | 的中 | 的中率 | 投資 | 払戻 | 収支 | ROI |\n|---|---:|---:|---:|---:|---:|---:|---:|\n${table(result.by_odds_source)}\n\n## 外れ分類\n${Object.entries(misses).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`- ${k}: ${fmt(v)}R`).join('\n')}\n\n## 注意\n${result.limitations.map(x=>`- ${x}`).join('\n')}\n`;
await fs.writeFile('reports/backtest-v60-2y.md',md);console.log(JSON.stringify(summary,null,2));